//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeirdBlacksmith.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponsModels
    {
        public int Id { get; set; }
        public string Rarity { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MinDamage { get; set; }
        public int MaxDamage { get; set; }
        public string ImageUrl { get; set; }
        public string Added { get; set; }
        public int TitleModelsId { get; set; }
    
        public virtual TitleModels TitleModels { get; set; }
    }
}
